FROM centos:stream8

ENV ANSIBLE_HOST_KEY_CHECKING false
ENV ANSIBLE_GATHERING smart
ENV ANSIBLE_RETRY_FILES_ENABLED false

RUN dnf -y install epel-release
RUN dnf groupinstall "Development Tools" -y &&\
  dnf install openssl-devel libffi-devel python3.9 bzip2-devel -y
RUN alternatives --set python /usr/bin/python3.9
RUN python --version
RUN dnf check-update; \
  dnf install -y gcc libffi-devel epel-release; \
  dnf install -y openssh-clients; \
  dnf install -y sshpass; \
  pip3 install --upgrade pip; \
  pip3 install ansible


WORKDIR /ansible
#ENTRYPOINT ["ansible-playbook","playbook.yml"]
ENTRYPOINT ["ansible-playbook"]
