---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6

collections:
# With just the collection name
#- kubernetes.core

# With the collection name, version, and source options
- name: kubernetes.core
  version: 2.3.2
  #source:
- name: community.postgresql
  version: 2.2.0
